### ISSUE TITLE
Markdown rendering doesn't seem ideal

### ISSUE THREAD

**Issue by nesium** [prose-im/prose-core-views#20]
Writing `F*ing nice` in a message gets rendered as if it were `F*ing nice*`

**Comment by valeriansaliou** [comment]
Sounds like it could be a `snarkdown` issue.

**Comment by nesium** [comment]
Jup. It also seems like code and quotes are not parsed/rendered properly. Although I don't know if we even have styles for that yet (quotes that is, code blocks I have seen).

**Comment by valeriansaliou** [comment]
No, we have no style for Markdown just yet. I'll open a separate issue for that.

**Comment by nesium** [comment]
Another case:

Text:
```
Feb 13 20:43:50 modulemanager   error   Error initializing module 'storage_sql' on 'proxy.ssk.pm': /usr/share/lua/5.1/pr
osody/util/startup.lua:203: module 'DBI' not found:No LuaRocks module found for DBI
        no field package.preload['DBI']
        no file './prosody/DBI.lua'
        no file './DBI.lua'
        no file '/usr/local/share/lua/5.1/prosody/DBI.lua'
        no file '/usr/local/share/lua/5.1/DBI.lua'
```

Result snarkdown:
<img width="650" alt="Screenshot 2024-02-14 at 13 43 55" src="https://github.com/prose-im/prose-core-views/assets/39174/7ba1e962-179e-4646-a986-6165d18cedb1">

Result Github:
<img width="770" alt="Screenshot 2024-02-14 at 13 47 38" src="https://github.com/prose-im/prose-core-views/assets/39174/c8f75b7f-e4aa-4972-b41a-5995e288a507">

I think we should use a "proper" Markdown parser, i.e. something that is tested against CommonMark.

**Comment by nesium** [comment]
Last example:

Text:
```
http://upload.nsm.chat:5280/file_share/bYBeUDWO9fctt0OrbX1eTStw/brooke-lark-kVCRP3uiLiE-unsplash.jpg
```

Result snarkdown:
<img width="537" alt="Screenshot 2024-02-14 at 14 20 19" src="https://github.com/prose-im/prose-core-views/assets/39174/6c59c8c2-55e5-4919-9c48-3dba2b6ab40c">

**Comment by valeriansaliou** [comment]
I may want to change Markdown library there, looks like it's causing too much trouble!

**Comment by nesium** [comment]
I'm going to reopen this. See examples…

<img width="722" alt="Screenshot 2024-04-17 at 10 39 52" src="https://github.com/prose-im/prose-core-views/assets/39174/2950eed8-25ea-4cad-9c6a-e0c3e4f90a31">

<img width="655" alt="Screenshot 2024-04-17 at 10 40 16" src="https://github.com/prose-im/prose-core-views/assets/39174/7adb3042-0bd6-4f2b-990f-d0f6069d39db">

**Comment by nesium** [comment]
New issue:

The message…

```
​```
1
2
3
​```
```

Renders as 

```
2
3
```

**Comment by nesium** [comment]
Lists only render at the beginning of the message or after a newline:

Works:
```
​```
- A
- B
​```
```

Works:
```
​```
Some text

- A
- B
​```
```

Does not work:
```
​```
Some text
- A
- B
​```
```

Github renders it as expected:

Some text
- A
- B

**Comment by valeriansaliou** [comment]
Closed since formatting is now produced by the core client.
