### ISSUE TITLE
Add CSS styles for Markdown

### ISSUE THREAD

**Issue by valeriansaliou** [prose-im/prose-core-views#21]
We currently don't have custom CSS style for `snarkdown`-rendered HTML, from Markdown. It'd be good to add style for eg. code blocks and such.

**Comment by valeriansaliou** [comment]
References #20

**Comment by nesium** [comment]
It would be ✨phenomenal ✨if we could have syntax highlighting for code blocks. 

```
​```ts
// highlighted code here
​```
```

**Comment by valeriansaliou** [comment]
Fixed in 46fced77068404c12a2fdec7f493cd87e21f2516 ; syntax highlighting coming later, as part of another issue.
