### ISSUE TITLE
Code syntax highlighting in Markdown code blocks

### ISSUE THREAD

**Issue by valeriansaliou** [prose-im/prose-core-views#23]
Add syntax highlighting for most common programming languages in code blocks. Only import highlighting rules for the _very_ most popular programming languages, so that the final build size does not get too large.

**Comment by nesium** [comment]
https://www.tiobe.com/tiobe-index/ (doesn't include things like JSON, YAML, etc. however)

Could the styles also be loaded lazily for less popular languages?

**Comment by valeriansaliou** [comment]
Use: https://github.com/speed-highlight/core
